import { Injectable } from '@nestjs/common';
import type { CashVoucher, Prisma } from '@prisma/client';

export interface CreateCashVoucherData {
  voucherNo: string;
  direction: 'EXPENSE' | 'INCOME';
  /** `null` cho phiếu Chuyển quỹ (`counterAccountId` có giá trị). */
  incomeExpenseTypeCode: string | null;
  cashAccountId: string;
  /** "Chuyển quỹ" (GĐ2) — có giá trị = phiếu này là Chuyển quỹ. */
  counterAccountId?: string | null;
  paymentMethodCode: string;
  amount: bigint;
  occurredAt: Date;
  partnerName?: string | null;
  description: string;
  note?: string | null;
  status: 'POSTED' | 'PENDING_APPROVAL';
  cashierShiftId: string | null;
  /** Phiếu Chuyển quỹ tự sinh lúc Chốt ca (Thủ quỹ riêng) — mặc định `false` (lập tay). */
  isAutoGenerated?: boolean;
}

export interface UpdateCashVoucherData {
  incomeExpenseTypeCode?: string | null;
  cashAccountId?: string;
  counterAccountId?: string | null;
  paymentMethodCode?: string;
  amount?: bigint;
  occurredAt?: Date;
  partnerName?: string | null;
  description?: string;
  note?: string | null;
}

/** 1 dòng đủ để dựng Sổ quỹ (GĐ2) — xem `CashBookReportService.getLedger()`. */
export interface CashVoucherLedgerRow {
  id: string;
  voucherNo: string;
  direction: 'EXPENSE' | 'INCOME';
  cashAccountId: string;
  counterAccountId: string | null;
  amount: bigint;
  occurredAt: Date;
  description: string;
  createdAt: Date;
}

export interface ListCashVouchersFilter {
  from?: Date;
  to?: Date;
  direction?: 'EXPENSE' | 'INCOME';
  status?: 'POSTED' | 'PENDING_APPROVAL' | 'REJECTED';
  cashierShiftId?: string;
}

/** 1 dòng đủ để nạp vào `computeCashierShiftTotals()` (@nexamed/core) — xem `CashierShiftService`. */
export interface CashVoucherCashierShiftRow {
  paymentMethodCode: string;
  direction: 'EXPENSE' | 'INCOME';
  amount: bigint;
}

/** Chỗ DUY NHẤT gọi Prisma cho bảng `cash_voucher` — theo .claude/docs/coding-standards.md. */
@Injectable()
export class CashVoucherRepository {
  create(tx: Prisma.TransactionClient, tenantId: string, actorId: string, data: CreateCashVoucherData): Promise<CashVoucher> {
    return tx.cashVoucher.create({
      data: {
        tenantId,
        voucherNo: data.voucherNo,
        direction: data.direction,
        incomeExpenseTypeCode: data.incomeExpenseTypeCode,
        cashAccountId: data.cashAccountId,
        counterAccountId: data.counterAccountId ?? null,
        paymentMethodCode: data.paymentMethodCode,
        amount: data.amount,
        occurredAt: data.occurredAt,
        partnerName: data.partnerName ?? null,
        description: data.description,
        note: data.note ?? null,
        status: data.status,
        cashierShiftId: data.cashierShiftId,
        isAutoGenerated: data.isAutoGenerated ?? false,
        createdBy: actorId,
        updatedBy: actorId,
      },
    });
  }

  /** Dùng cho các đường EDIT (sửa/huỷ/duyệt/từ chối/in) — phiếu đã huỷ (soft-delete) trả `null`,
   * chặn thao tác lặp lại trên phiếu đã huỷ (đúng khuôn mọi repository khác trong dự án). */
  findById(tx: Prisma.TransactionClient, tenantId: string, id: string): Promise<CashVoucher | null> {
    return tx.cashVoucher.findFirst({ where: { tenantId, id, deletedAt: null } });
  }

  /** Dùng cho đường XEM (GET chi tiết) — KHÔNG lọc `deletedAt`, phiếu đã huỷ vẫn xem được (chỉ
   * đọc), tránh "biến mất" khó hiểu. Web tự ẩn mọi nút thao tác khi `voided=true`. */
  findByIdAny(tx: Prisma.TransactionClient, tenantId: string, id: string): Promise<CashVoucher | null> {
    return tx.cashVoucher.findFirst({ where: { tenantId, id } });
  }

  /** Danh sách — cùng lý do `findByIdAny`, KHÔNG lọc `deletedAt` để phiếu đã huỷ vẫn hiện (kèm badge).
   * Sắp `occurredAt desc` (Ngày phát sinh do người dùng chọn, chỉ có độ chính xác NGÀY — 2 phiếu
   * cùng ngày sẽ hoà); thêm tie-break `createdAt desc` (thời điểm ghi nhận thật, có độ chính xác tới
   * mili-giây) để phiếu lập SAU vẫn luôn hiện TRƯỚC khi cùng ngày phát sinh — chủ dự án phát hiện
   * 2026-09-07: thiếu tie-break khiến phiếu mới tạo lại rơi XUỐNG DƯỚI phiếu cũ hơn (thứ tự vật lý
   * trong bảng, không đảm bảo). */
  list(tx: Prisma.TransactionClient, tenantId: string, filter: ListCashVouchersFilter): Promise<CashVoucher[]> {
    return tx.cashVoucher.findMany({
      where: {
        tenantId,
        occurredAt: { gte: filter.from, lte: filter.to },
        direction: filter.direction,
        status: filter.status,
        cashierShiftId: filter.cashierShiftId,
      },
      orderBy: [{ occurredAt: 'desc' }, { createdAt: 'desc' }],
    });
  }

  async updateIfVersionMatches(
    tx: Prisma.TransactionClient,
    tenantId: string,
    id: string,
    expectedVersion: number,
    actorId: string,
    data: UpdateCashVoucherData,
  ): Promise<number> {
    const result = await tx.cashVoucher.updateMany({
      where: { tenantId, id, version: expectedVersion, deletedAt: null },
      data: { ...data, updatedBy: actorId, version: { increment: 1 } },
    });
    return result.count;
  }

  /** "Huỷ phiếu" — soft-delete, lý do bắt buộc (CLAUDE.md: không xoá cứng). `status` giữ nguyên
   * (KHÔNG thêm giá trị VOIDED) — mọi truy vấn khác đã lọc `deletedAt: null` nên tự loại trừ. */
  async voidById(tx: Prisma.TransactionClient, tenantId: string, id: string, expectedVersion: number, actorId: string, reason: string): Promise<number> {
    const result = await tx.cashVoucher.updateMany({
      where: { tenantId, id, version: expectedVersion, deletedAt: null },
      data: { deletedAt: new Date(), deletedReason: reason, updatedBy: actorId, version: { increment: 1 } },
    });
    return result.count;
  }

  /** Duyệt — chỉ áp dụng đúng phiếu đang `PENDING_APPROVAL` (điều kiện `WHERE` chặn race 2 người
   * duyệt/từ chối cùng lúc, cùng kỹ thuật `InvoiceRepository.markPaid()`). */
  async approve(tx: Prisma.TransactionClient, tenantId: string, id: string, expectedVersion: number, actorId: string): Promise<number> {
    const result = await tx.cashVoucher.updateMany({
      where: { tenantId, id, version: expectedVersion, deletedAt: null, status: 'PENDING_APPROVAL' },
      data: { status: 'POSTED', approvedBy: actorId, approvedAt: new Date(), updatedBy: actorId, version: { increment: 1 } },
    });
    return result.count;
  }

  async reject(tx: Prisma.TransactionClient, tenantId: string, id: string, expectedVersion: number, actorId: string, reason: string): Promise<number> {
    const result = await tx.cashVoucher.updateMany({
      where: { tenantId, id, version: expectedVersion, deletedAt: null, status: 'PENDING_APPROVAL' },
      data: { status: 'REJECTED', rejectionReason: reason, updatedBy: actorId, version: { increment: 1 } },
    });
    return result.count;
  }

  markPrintedIfNotYet(tx: Prisma.TransactionClient, tenantId: string, id: string, actorId: string): Promise<Prisma.BatchPayload> {
    return tx.cashVoucher.updateMany({ where: { tenantId, id, printedAt: null }, data: { printedAt: new Date(), updatedBy: actorId } });
  }

  /**
   * "Chốt ca" — mọi phiếu ĐÃ DUYỆT (`status='POSTED'`) trong khoảng [startAt, endAt), lọc theo
   * `createdAt` (thời điểm tiền THẬT SỰ đổi tay) — KHÔNG phải `occurredAt` (ngày phát sinh do
   * người dùng tự khai, có thể lùi ngày để ghi sổ trễ, không phản ánh đúng lúc tiền rời/vào két).
   * Cùng khuôn `PaymentRepository.listForWindow()`.
   */
  listPostedForWindow(tx: Prisma.TransactionClient, tenantId: string, startAt: Date, endAt: Date): Promise<CashVoucherCashierShiftRow[]> {
    return tx.cashVoucher.findMany({
      where: { tenantId, deletedAt: null, status: 'POSTED', createdAt: { gte: startAt, lt: endAt } },
      select: { paymentMethodCode: true, direction: true, amount: true },
    });
  }

  /** "Đa thu ngân" — mọi phiếu ĐÃ DUYỆT gắn ĐÚNG ca này, cùng khuôn `PaymentRepository.listForShift()`. */
  listPostedForShift(tx: Prisma.TransactionClient, tenantId: string, cashierShiftId: string): Promise<CashVoucherCashierShiftRow[]> {
    return tx.cashVoucher.findMany({
      where: { tenantId, deletedAt: null, status: 'POSTED', cashierShiftId },
      select: { paymentMethodCode: true, direction: true, amount: true },
    });
  }

  /**
   * "Sổ quỹ" (GĐ2) — mọi phiếu ĐÃ DUYỆT (`status='POSTED'`) mà quỹ `cashAccountId` là quỹ NGUỒN
   * (`cashAccountId=X`) HOẶC quỹ ĐÍCH của 1 phiếu Chuyển quỹ (`counterAccountId=X`) — 1 phiếu
   * Chuyển quỹ xuất hiện ở CẢ HAI Sổ quỹ (2 chiều), đúng thiết kế đã chốt. Sắp CŨ→MỚI để tính số
   * dư luỹ kế tự nhiên (khác List Screen khác trong app).
   */
  listForAccountLedger(tx: Prisma.TransactionClient, tenantId: string, cashAccountId: string, from?: Date, to?: Date): Promise<CashVoucherLedgerRow[]> {
    return tx.cashVoucher.findMany({
      where: {
        tenantId,
        deletedAt: null,
        status: 'POSTED',
        OR: [{ cashAccountId }, { counterAccountId: cashAccountId }],
        occurredAt: { gte: from, lte: to },
      },
      select: { id: true, voucherNo: true, direction: true, cashAccountId: true, counterAccountId: true, amount: true, occurredAt: true, description: true, createdAt: true },
      orderBy: { occurredAt: 'asc' },
    });
  }

  /**
   * "Báo cáo dòng tiền" (GĐ2) — mọi phiếu ĐÃ DUYỆT trong khoảng [from, to] (MỌI quỹ) — dùng gộp
   * bucket theo Loại thu chi (`byType`, loại trừ Chuyển quỹ) và phân bổ theo quỹ (`byAccount`, GỒM
   * cả Chuyển quỹ 2 chiều).
   */
  listPostedForReport(tx: Prisma.TransactionClient, tenantId: string, from: Date, to: Date) {
    return tx.cashVoucher.findMany({
      where: { tenantId, deletedAt: null, status: 'POSTED', occurredAt: { gte: from, lte: to } },
      select: { direction: true, amount: true, cashAccountId: true, counterAccountId: true, incomeExpenseTypeCode: true },
    });
  }

  /** Tổng luỹ kế TRƯỚC mốc `before` cho quỹ `cashAccountId` — dùng tính "Số dư đầu kỳ" của Sổ quỹ
   * khi có `from`. Trả 2 tổng riêng (nguồn bị trừ / đích được cộng) — `CashBookReportService` tự
   * áp dấu đúng theo `direction`. */
  async sumBeforeForAccount(tx: Prisma.TransactionClient, tenantId: string, cashAccountId: string, before: Date): Promise<{ asSourceIncome: bigint; asSourceExpense: bigint; asCounter: bigint }> {
    const rows = await tx.cashVoucher.findMany({
      where: { tenantId, deletedAt: null, status: 'POSTED', OR: [{ cashAccountId }, { counterAccountId: cashAccountId }], occurredAt: { lt: before } },
      select: { direction: true, amount: true, cashAccountId: true, counterAccountId: true },
    });
    let asSourceIncome = 0n;
    let asSourceExpense = 0n;
    let asCounter = 0n;
    for (const row of rows) {
      if (row.cashAccountId === cashAccountId) {
        if (row.direction === 'INCOME') asSourceIncome += row.amount;
        else asSourceExpense += row.amount;
      } else {
        // counterAccountId === cashAccountId (phiếu Chuyển quỹ, quỹ này là ĐÍCH) — luôn được CỘNG,
        // bất kể direction ghi trên phiếu (direction mô tả tác động lên cashAccountId, không phải quỹ đích).
        asCounter += row.amount;
      }
    }
    return { asSourceIncome, asSourceExpense, asCounter };
  }
}
