/**
 * Dữ liệu khởi tạo danh mục "Dị nguyên" (docs/DECISIONS.md #069/#070) — chủ dự án cung cấp qua
 * `docs/data/allergen-catalog.md` (copy byte-for-byte vào repo, đúng tiền lệ `icd10-chuong-*.md`).
 * Nhúng trực tiếp thành mảng TS (quy mô 150 dòng, không cần kỹ thuật JSON string như ICD-10
 * 15.844 dòng). Thứ tự nhóm giữ đúng thứ tự xuất hiện LẦN ĐẦU trong file gốc — "Môi trường" xuất
 * hiện 2 đoạn rời nhau trong file gốc (dòng 93-100 và 117-121), đã gộp lại đúng 1 nhóm ở đây.
 * `seedAllergenCatalog()` (apps/api) dùng mảng này để tạo `AllergenGroup`/`Allergen` — mã (`code`)
 * KHÔNG có trong nguồn dữ liệu (tự sinh lúc seed, đúng quyết định #069 "mã phải tự phát sinh").
 */
export interface AllergenGroupSeed {
  groupName: string;
  items: string[];
}

export const ALLERGEN_CATALOG_SEED: AllergenGroupSeed[] = [
  {
    groupName: 'Thuốc',
    items: [
      'Penicillin',
      'Amoxicillin',
      'Ampicillin',
      'Oxacillin',
      'Piperacillin',
      'Piperacillin/Tazobactam',
      'Cephalexin',
      'Cefazolin',
      'Cefuroxime',
      'Cefixime',
      'Ceftriaxone',
      'Ceftazidime',
      'Cefotaxime',
      'Imipenem',
      'Meropenem',
      'Sulfonamide',
      'Cotrimoxazole',
      'Ciprofloxacin',
      'Levofloxacin',
      'Moxifloxacin',
      'Tetracycline',
      'Doxycycline',
      'Erythromycin',
      'Azithromycin',
      'Clarithromycin',
      'Metronidazole',
      'Clindamycin',
      'Aspirin',
      'Ibuprofen',
      'Diclofenac',
      'Naproxen',
      'Ketoprofen',
      'Ketorolac',
      'Paracetamol',
      'Acetaminophen',
      'Lidocaine',
      'Procaine',
      'Bupivacaine',
      'Morphine',
      'Codeine',
      'Tramadol',
      'Heparin',
      'Insulin',
      'Furosemide',
      'Omeprazole',
      'Pantoprazole',
      'Phenytoin',
      'Carbamazepine',
      'Lamotrigine',
      'Allopurinol',
    ],
  },
  {
    groupName: 'Thực phẩm',
    items: [
      'Sữa bò',
      'Trứng gà',
      'Trứng vịt',
      'Đậu phộng (lạc)',
      'Đậu nành',
      'Hạnh nhân',
      'Hạt điều',
      'Óc chó',
      'Hạt dẻ',
      'Hạt mắc ca',
      'Hạt dẻ cười',
      'Mè (vừng)',
      'Lúa mì',
      'Gạo',
      'Yến mạch',
      'Tôm',
      'Cua',
      'Ghẹ',
      'Tôm hùm',
      'Nghêu',
      'Sò',
      'Hàu',
      'Mực',
      'Bạch tuộc',
      'Cá ngừ',
      'Cá hồi',
      'Cá thu',
      'Cá tuyết',
      'Cá trích',
      'Cá basa',
      'Thịt bò',
      'Thịt heo',
      'Thịt gà',
      'Thịt cừu',
      'Xoài',
      'Dứa (thơm)',
      'Kiwi',
      'Dâu tây',
      'Chuối',
      'Đào',
    ],
  },
  {
    groupName: 'Môi trường',
    items: [
      'Mạt bụi nhà',
      'Bụi nhà',
      'Phấn hoa cỏ',
      'Phấn hoa cây',
      'Phấn hoa cỏ dại',
      'Nấm mốc',
      'Aspergillus',
      'Cladosporium',
      'Lông chim',
      'Lông vũ',
      'Mạt kho',
      'Mạt bột',
      'Dander động vật',
    ],
  },
  {
    groupName: 'Động vật',
    items: ['Mèo', 'Chó', 'Ngựa', 'Thỏ', 'Chuột', 'Chuột cống'],
  },
  {
    groupName: 'Côn trùng',
    items: ['Ong mật', 'Ong vò vẽ', 'Ong bắp cày', 'Kiến lửa', 'Muỗi', 'Bọ chét', 'Gián', 'Nhện', 'Rệp giường', 'Ruồi'],
  },
  {
    groupName: 'Tiếp xúc',
    items: [
      'Latex/cao su tự nhiên',
      'Nickel (niken)',
      'Chromium (crom)',
      'Cobalt',
      'Nhựa acrylic',
      'Nhựa epoxy',
      'Formaldehyde',
      'Paraben',
      'Hương liệu',
      'Nước hoa',
      'Mỹ phẩm',
      'Thuốc nhuộm tóc',
      'P-Phenylenediamine',
      'Xà phòng',
      'Chất tẩy rửa',
      'Chlorhexidine',
      'Povidone-iodine',
      'Neomycin',
      'Bacitracin',
      'Benzocaine',
      'Keo dán y tế',
      'Băng dính y tế',
      'Acrylic nha khoa',
      'Thuốc trừ sâu',
      'Chất bảo quản',
      'Ammonia',
      'Clo',
      'Chất tẩy trắng',
      'Bột giặt',
      'Dung môi hữu cơ',
    ],
  },
  {
    groupName: 'Khác',
    items: ['Dị nguyên khác/không xác định'],
  },
];
