/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Đăng nhập bằng tenantId + username + password */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        tenantId: string;
                        username: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Đăng nhập thành công */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                accessToken: string;
                                expiresIn: number;
                                user: {
                                    /** Format: uuid */
                                    id: string;
                                    username: string;
                                    fullName: string;
                                    roles: ("receptionist" | "nurse" | "doctor" | "clinic_admin" | "system_admin")[];
                                };
                            };
                            meta: Record<string, never>;
                        };
                    };
                };
                /** @description Sai tenantId/username/password */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                            };
                        };
                    };
                };
                /** @description Tài khoản đã bị vô hiệu hoá */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                            };
                        };
                    };
                };
                /** @description Tài khoản đang bị khoá tạm sau nhiều lần đăng nhập sai */
                423: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Xoay vòng refresh token (đọc từ cookie httpOnly), cấp access token mới */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Refresh thành công */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                accessToken: string;
                                expiresIn: number;
                            };
                            meta: Record<string, never>;
                        };
                    };
                };
                /** @description Refresh token thiếu, sai, hết hạn, hoặc đã bị thu hồi */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Đăng xuất — thu hồi phiên refresh token hiện tại */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Đăng xuất thành công */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                success: boolean;
                            };
                            meta: Record<string, never>;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Danh tính + vai trò của user đang đăng nhập (khôi phục phiên lúc reload trang) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Thành công */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** Format: uuid */
                                id: string;
                                username: string;
                                fullName: string;
                                roles: ("receptionist" | "nurse" | "doctor" | "clinic_admin" | "system_admin")[];
                            };
                            meta: Record<string, never>;
                        };
                    };
                };
                /** @description Thiếu hoặc sai access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/break-glass": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Xin vượt quyền tạm thời — xác thực lại mật khẩu + lý do bắt buộc */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        entityType: string;
                        /** Format: uuid */
                        entityId: string;
                        reason: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Tạo phiên break-glass thành công */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** Format: date-time */
                                expiresAt: string;
                            };
                            meta: Record<string, never>;
                        };
                    };
                };
                /** @description Thiếu access token hoặc sai mật khẩu */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Danh sách bệnh nhân, phân trang cursor (PAT-02) */
        get: {
            parameters: {
                query?: {
                    cursor?: string;
                    limit?: number;
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Thành công */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                items: {
                                    /** Format: uuid */
                                    id: string;
                                    patientCode: string;
                                    fullName: string;
                                    dob: string;
                                    /** @enum {string} */
                                    gender: "male" | "female" | "other";
                                    phone: string;
                                    hasNationalId: boolean;
                                    version: number;
                                }[];
                                nextCursor: string | null;
                            };
                            meta: Record<string, never>;
                        };
                    };
                };
                /** @description Thiếu hoặc sai access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                            };
                        };
                    };
                };
                /** @description Không có quyền patient.read */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        /** Tạo hồ sơ bệnh nhân (PAT-01) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        fullName: string;
                        /** Format: date */
                        dob: string;
                        /** @enum {string} */
                        gender: "male" | "female" | "other";
                        phone: string;
                        nationalId?: string;
                        address?: {
                            street?: string;
                            ward?: string;
                            district?: string;
                            province?: string;
                        };
                        allergyNote?: string;
                    };
                };
            };
            responses: {
                /** @description Tạo thành công */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** Format: uuid */
                                id: string;
                                patientCode: string;
                                fullName: string;
                                dob: string;
                                /** @enum {string} */
                                gender: "male" | "female" | "other";
                                phone: string;
                                hasNationalId: boolean;
                                version: number;
                                nationalId: string | null;
                                address: {
                                    street?: string;
                                    ward?: string;
                                    district?: string;
                                    province?: string;
                                } | null;
                                allergyNote: string | null;
                                /** Format: uuid */
                                mergedIntoId: string | null;
                            };
                            meta: Record<string, never>;
                        };
                    };
                };
                /** @description Thiếu hoặc sai access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                            };
                        };
                    };
                };
                /** @description Không có quyền patient.create */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                            };
                        };
                    };
                };
                /** @description Trùng số CCCD/CMND với bệnh nhân khác trong tenant */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chi tiết một hồ sơ bệnh nhân (kèm CCCD đã giải mã) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Thành công */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** Format: uuid */
                                id: string;
                                patientCode: string;
                                fullName: string;
                                dob: string;
                                /** @enum {string} */
                                gender: "male" | "female" | "other";
                                phone: string;
                                hasNationalId: boolean;
                                version: number;
                                nationalId: string | null;
                                address: {
                                    street?: string;
                                    ward?: string;
                                    district?: string;
                                    province?: string;
                                } | null;
                                allergyNote: string | null;
                                /** Format: uuid */
                                mergedIntoId: string | null;
                            };
                            meta: Record<string, never>;
                        };
                    };
                };
                /** @description Thiếu hoặc sai access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                            };
                        };
                    };
                };
                /** @description Không có quyền patient.read (có thể xin break-glass) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                            };
                        };
                    };
                };
                /** @description Không tìm thấy hồ sơ (không tồn tại hoặc thuộc tenant khác) */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Sửa hồ sơ bệnh nhân — bắt buộc kèm version hiện có (optimistic locking) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        fullName?: string;
                        /** Format: date */
                        dob?: string;
                        /** @enum {string} */
                        gender?: "male" | "female" | "other";
                        phone?: string;
                        nationalId?: string;
                        address?: {
                            street?: string;
                            ward?: string;
                            district?: string;
                            province?: string;
                        };
                        allergyNote?: string;
                        version: number;
                    };
                };
            };
            responses: {
                /** @description Sửa thành công */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** Format: uuid */
                                id: string;
                                patientCode: string;
                                fullName: string;
                                dob: string;
                                /** @enum {string} */
                                gender: "male" | "female" | "other";
                                phone: string;
                                hasNationalId: boolean;
                                version: number;
                                nationalId: string | null;
                                address: {
                                    street?: string;
                                    ward?: string;
                                    district?: string;
                                    province?: string;
                                } | null;
                                allergyNote: string | null;
                                /** Format: uuid */
                                mergedIntoId: string | null;
                            };
                            meta: Record<string, never>;
                        };
                    };
                };
                /** @description Thiếu hoặc sai access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                            };
                        };
                    };
                };
                /** @description Không có quyền patient.update (có thể xin break-glass) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                            };
                        };
                    };
                };
                /** @description Không tìm thấy hồ sơ (không tồn tại hoặc thuộc tenant khác) */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                            };
                        };
                    };
                };
                /** @description version không khớp (dữ liệu đã đổi) hoặc trùng CCCD với bệnh nhân khác */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                            };
                        };
                    };
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
