import type {
  ClinicalOrderDetail,
  CashierShiftDetail,
  CashVoucher,
  ClinicPrintHeader,
  CombinedInvoicePrintResponse,
  Invoice,
  InvoiceLine,
  PrescriptionItem,
  StockCountDetail,
  StockIssueDetail,
  StockReceiptDetail,
  StockTransferDetail,
} from '@nexamed/shared';

/**
 * Dữ liệu MẪU cho phần xem trước ở "Quản lý mẫu in" (docs/DECISIONS.md #211) — để phòng khám mới cài, CHƯA có bệnh nhân/
 * phiếu nào, vẫn chỉnh và in thử được. Xem trước dựng bằng CHÍNH component in thật của từng chứng từ với dữ liệu này
 * (không có bản vẽ riêng), nên bản xem trước luôn khớp bản in. Tên người/thuốc đa dạng, không số liệu thống kê bịa.
 */
const NOW = '2026-10-01T07:30:00.000Z';
const ID = (n: number) => `00000000-0000-4000-8000-${String(n).padStart(12, '0')}`;

/** Logo giữ chỗ (SVG nội tuyến) — phòng khám chưa tải logo in vẫn thấy vị trí logo ở bản xem trước. */
const SAMPLE_LOGO =
  "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='64' height='64'><rect x='1' y='1' width='62' height='62' rx='6' fill='white' stroke='%2394a3b8'/><text x='32' y='37' font-size='13' text-anchor='middle' fill='%2394a3b8' font-family='sans-serif'>LOGO</text></svg>";

/** Đầu trang mẫu — dùng khi phòng khám chưa nhập "Thông tin phòng khám"; có thì xem trước dùng thông tin THẬT. */
export const SAMPLE_CLINIC_HEADER: ClinicPrintHeader = {
  name: 'Phòng khám Đa khoa Minh Đức',
  address: '128 Lê Lợi, P. Bến Thành, TP. Hồ Chí Minh',
  phone: '028 3822 1456',
  taxCode: '0312345678',
  printLogoUrl: SAMPLE_LOGO,
};

export const SAMPLE_PRESCRIPTION_ITEMS: PrescriptionItem[] = [
  {
    id: ID(1),
    drugId: ID(101),
    drugName: 'Amoxicillin + Acid clavulanic 625mg',
    freeTextDrugName: null,
    activeIngredient: 'Amoxicillin, Acid clavulanic',
    doseMorning: 1,
    doseNoon: 0,
    doseAfternoon: 0,
    doseEvening: 1,
    durationDays: 7,
    quantity: 14,
    unitCode: 'VIEN',
    instruction: 'Uống sau ăn',
  },
  {
    id: ID(2),
    drugId: ID(102),
    drugName: 'Acetylcystein 200mg',
    freeTextDrugName: null,
    activeIngredient: 'Acetylcystein',
    doseMorning: 1,
    doseNoon: 1,
    doseAfternoon: 0,
    doseEvening: 1,
    durationDays: 7,
    quantity: 21,
    unitCode: 'GOI',
    instruction: 'Hoà với nửa ly nước',
  },
  {
    id: ID(3),
    drugId: ID(103),
    drugName: 'Paracetamol 500mg',
    freeTextDrugName: null,
    activeIngredient: 'Paracetamol',
    doseMorning: 0,
    doseNoon: 0,
    doseAfternoon: 0,
    doseEvening: 0,
    durationDays: 5,
    quantity: 10,
    unitCode: 'VIEN',
    instruction: 'Uống khi sốt trên 38,5°C, cách nhau 6 giờ',
  },
];

function invoiceLine(n: number, name: string, unitPrice: number, quantity: number, source: 'SERVICE' | 'DRUG' = 'SERVICE'): InvoiceLine {
  return {
    id: ID(200 + n),
    examTypeCode: `DV${n}`,
    examTypeName: name,
    priceTypeCode: null,
    unitCode: null,
    unitPrice,
    quantity,
    lineTotal: unitPrice * quantity,
    discountType: null,
    discountValue: null,
    discountAmount: 0,
    lineSource: source,
    clinicalOrderNo: null,
    stockIssueNo: null,
    netAmount: unitPrice * quantity,
    refundedQuantity: 0,
    refundedAmount: 0,
  };
}

export const SAMPLE_INVOICE: Invoice = {
  id: ID(300),
  encounterId: ID(301),
  invoiceNo: 'PT2610000184',
  invoiceType: 'SERVICE',
  status: 'PAID',
  totalAmount: 450000,
  lines: [invoiceLine(1, 'Khám nội tổng quát', 200000, 1), invoiceLine(2, 'Siêu âm ổ bụng', 250000, 1)],
  discountMode: 'NONE',
  discountType: null,
  discountValue: null,
  discountReason: null,
  discountAmount: 0,
  dueAmount: 450000,
  encounterNo: 'LK2610000471',
  checkedInAt: NOW,
  patientId: ID(302),
  patientCode: 'BN2609000471',
  fullName: 'Lý Thị Hoài Thương',
  departmentName: 'Khoa Nội tổng quát',
  encounterVersion: 1,
  printedAt: null,
  pendingPaymentMethod: null,
  pendingCashReceivedAmount: null,
  paymentMethod: 'CASH',
  paidAt: NOW,
  payments: [{ method: 'CASH', amount: 450000 }],
  encounterCancelled: false,
  needsRefund: false,
  refundedAt: null,
  refundReason: null,
  otherInvoices: [],
  refundedAmount: 0,
  refunds: [],
  version: 1,
};

export const SAMPLE_COMBINED_INVOICES: CombinedInvoicePrintResponse = {
  invoices: [
    SAMPLE_INVOICE,
    {
      ...SAMPLE_INVOICE,
      id: ID(310),
      invoiceNo: 'PT2610000185',
      invoiceType: 'DRUG',
      totalAmount: 168000,
      dueAmount: 168000,
      lines: [{ ...invoiceLine(3, 'Amoxicillin + Acid clavulanic 625mg', 12000, 14, 'DRUG'), stockIssueNo: 'PX2610000052' }],
      payments: [{ method: 'CASH', amount: 168000 }],
    },
  ],
  totals: { invoiceCount: 2, grossAmount: 618000, discountAmount: 0, paidAmount: 618000, refundedAmount: 0, unpaidAmount: 0 },
};

export const SAMPLE_CASH_VOUCHER: CashVoucher = {
  id: ID(400),
  voucherNo: 'PC2610000023',
  direction: 'EXPENSE',
  incomeExpenseTypeCode: 'TC00001',
  cashAccountId: ID(401),
  counterAccountId: null,
  paymentMethodCode: 'CASH',
  amount: 850000,
  occurredAt: NOW,
  partnerName: 'Công ty Điện lực Quận 1',
  description: 'Tiền điện tháng 09/2026',
  note: 'Hoá đơn số 0004718',
  status: 'POSTED',
  voided: false,
  approvedByName: null,
  approvedAt: null,
  rejectionReason: null,
  createdByName: 'Nguyễn Thị Bích Ngọc',
  printedAt: null,
  isAutoGenerated: false,
  version: 1,
};

export const SAMPLE_WALLET_RECEIPT = {
  voucherNo: 'NV2610000009',
  occurredAt: NOW,
  patientFullName: 'Lý Thị Hoài Thương',
  patientCode: 'BN2609000471',
  note: 'Tạm ứng thủ thuật tiểu phẫu',
  paymentMethodLabel: 'Tiền mặt',
  balanceBefore: 200000,
  balanceAfter: 700000,
  amount: 500000,
};

export const SAMPLE_CASHIER_SHIFT: CashierShiftDetail = {
  id: ID(500),
  shiftNo: 'CC2610000012',
  cashierId: ID(501),
  cashierName: 'Nguyễn Thị Bích Ngọc',
  shiftLabel: 'Ca sáng',
  status: 'CLOSED',
  openedAt: '2026-10-01T01:00:00.000Z',
  openingFloatExpected: 2000000,
  openingFloatActual: 2000000,
  openingDiscrepancyReason: null,
  closedAt: '2026-10-01T05:30:00.000Z',
  cashInAmount: 5650000,
  cashOutAmount: 200000,
  nonCashBreakdown: [{ method: 'TRANSFER', methodLabel: 'Chuyển khoản', count: 4, amount: 1820000 }],
  expectedCashAmount: 7450000,
  otherCashInAmount: 0,
  otherCashOutAmount: 0,
  countedCashAmount: 7450000,
  cashDiscrepancyReason: null,
  keepForNextAmount: 2000000,
  submittedAmount: 5450000,
  handoverNote: null,
  resolutionMethod: null,
  resolutionNote: null,
  resolvedByName: null,
  resolvedAt: null,
  approvedByName: null,
  approvedAt: null,
  editedByName: null,
  editedAt: null,
  version: 1,
};

export const SAMPLE_UNIT_NAMES = new Map<string, string>([
  ['VIEN', 'Viên'],
  ['HOP', 'Hộp'],
]);

export const SAMPLE_STOCK_RECEIPT: StockReceiptDetail = {
  id: ID(600),
  receiptNo: 'PN2610000031',
  receiptType: 'PURCHASE',
  status: 'POSTED',
  warehouseId: ID(601),
  warehouseName: 'Kho thuốc chính',
  supplierId: ID(602),
  supplierName: 'Công ty CP Dược phẩm Hà Thành',
  occurredAt: NOW,
  note: 'Giao hàng đợt 2 tháng 10',
  supplierInvoiceNo: 'HD-0045211',
  totalAmount: 6150000,
  discountType: null,
  discountValue: null,
  discountReason: null,
  prepaidAmount: 0,
  prepaidPaymentMethodCode: null,
  prepaidCashAccountId: null,
  prepaidVoucherId: null,
  sourceIssueId: null,
  sourceIssueNo: null,
  lineCount: 2,
  createdByName: 'Phạm Quốc Việt',
  approvedByName: 'Đặng Quốc Hưng',
  approvedAt: NOW,
  rejectionReason: null,
  voided: false,
  version: 1,
  discountMode: 'NONE',
  discountAmount: 0,
  netAmount: 6150000,
  lines: [
    { id: ID(610), drugId: ID(101), drugCode: 'THUOC-0012', drugName: 'Paracetamol 500mg', unitCode: 'HOP', quantity: 30, unitCost: 45000, batchNo: 'L2610A', expiryDate: '2028-09-30', lineAmount: 1350000, discountType: null, discountValue: null, discountAmount: 0 },
    { id: ID(611), drugId: ID(102), drugCode: 'THUOC-0031', drugName: 'Amoxicillin + Acid clavulanic 625mg', unitCode: 'HOP', quantity: 40, unitCost: 120000, batchNo: 'L2610B', expiryDate: '2028-06-30', lineAmount: 4800000, discountType: null, discountValue: null, discountAmount: 0 },
  ],
};

export const SAMPLE_STOCK_ISSUE: StockIssueDetail = {
  id: ID(700),
  issueNo: 'PX2610000052',
  issueType: 'RETAIL_SALE',
  status: 'POSTED',
  warehouseId: ID(601),
  warehouseName: 'Kho thuốc chính',
  prescriptionId: ID(701),
  encounterId: ID(301),
  patientCode: 'BN2609000471',
  patientFullName: 'Lý Thị Hoài Thương',
  occurredAt: NOW,
  note: null,
  totalAmount: 168000,
  lineCount: 1,
  createdByName: 'Phạm Quốc Việt',
  approvedByName: null,
  approvedAt: null,
  rejectionReason: null,
  departmentId: null,
  departmentName: null,
  voidedByName: null,
  voidedAt: null,
  voidReason: null,
  version: 1,
  supplierId: null,
  supplierName: null,
  sourceReceiptId: null,
  sourceReceiptNo: null,
  lines: [{ id: ID(710), prescriptionItemId: ID(1), drugId: ID(102), drugCode: 'THUOC-0031', drugName: 'Amoxicillin + Acid clavulanic 625mg', batchId: ID(711), batchNo: 'L2610B', quantity: 14, unitCost: 8500, sellPrice: 12000, lineAmount: 168000, returnUnitPrice: null }],
  attachedInvoice: null,
};

export const SAMPLE_STOCK_COUNT: StockCountDetail = {
  id: ID(800),
  countNo: 'KK2610000007',
  status: 'POSTED',
  warehouseId: ID(601),
  warehouseName: 'Kho thuốc chính',
  occurredAt: NOW,
  note: 'Kiểm kê cuối tháng',
  lineCount: 2,
  createdByName: 'Phạm Quốc Việt',
  approvedByName: 'Đặng Quốc Hưng',
  approvedAt: NOW,
  approvalReason: 'Hao hụt do vỡ khi vận chuyển',
  rejectionReason: null,
  version: 1,
  lines: [
    { id: ID(810), drugId: ID(101), drugCode: 'THUOC-0012', drugName: 'Paracetamol 500mg', isBatchManaged: true, batchId: ID(811), batchNo: 'L2610A', expiryDate: '2028-09-30', isNewBatch: false, systemQuantitySnapshot: 300, countedQuantity: 298, difference: -2 },
    { id: ID(812), drugId: ID(102), drugCode: 'THUOC-0031', drugName: 'Amoxicillin + Acid clavulanic 625mg', isBatchManaged: true, batchId: ID(813), batchNo: 'L2610B', expiryDate: '2028-06-30', isNewBatch: false, systemQuantitySnapshot: 120, countedQuantity: 120, difference: 0 },
  ],
};

export const SAMPLE_STOCK_TRANSFER: StockTransferDetail = {
  id: ID(900),
  transferNo: 'DC2610000004',
  status: 'COMPLETED',
  fromWarehouseId: ID(601),
  fromWarehouseName: 'Kho thuốc chính',
  toWarehouseId: ID(901),
  toWarehouseName: 'Tủ thuốc phòng khám 2',
  occurredAt: NOW,
  note: null,
  lineCount: 1,
  createdByName: 'Phạm Quốc Việt',
  shippedByName: 'Phạm Quốc Việt',
  shippedAt: NOW,
  receivedByName: 'Trần Minh Khuê',
  receivedAt: NOW,
  rejectionReason: null,
  version: 1,
  lines: [{ id: ID(910), drugId: ID(101), drugCode: 'THUOC-0012', drugName: 'Paracetamol 500mg', isBatchManaged: true, batchId: ID(811), batchNo: 'L2610A', expiryDate: '2028-09-30', quantityShipped: 50, quantityReceived: 50, varianceNote: null }],
};

/** Phiếu chỉ định cận lâm sàng mẫu (Cận lâm sàng GĐ3, #212) — dữ liệu minh hoạ cho bản xem trước ở Quản lý mẫu in. */
export const SAMPLE_CLINICAL_ORDER: ClinicalOrderDetail = {
  id: '00000000-0000-4000-8000-0000000000c1',
  orderNo: 'CLS2610000312',
  encounterId: '00000000-0000-4000-8000-0000000000e1',
  version: 1,
  createdAt: '2026-10-06T02:30:00.000Z',
  inHouseTotal: 680000,
  invoices: [],
  packages: [],
  items: [
    { id: 'i1', itemKind: 'TECHNICAL_SERVICE', technicalServiceId: null, examTypeCode: null, code: 'XN0014', name: 'Định lượng Glucose lúc đói [Huyết tương]', performance: 'IN_HOUSE', quantity: 1, unitPrice: 80000, lineTotal: 80000, packageId: null, placeName: 'P. Xét nghiệm', note: null, status: 'ORDERED', editable: true },
    { id: 'i2', itemKind: 'TECHNICAL_SERVICE', technicalServiceId: null, examTypeCode: null, code: 'XN0027', name: 'Định lượng HbA1c [Máu toàn phần]', performance: 'IN_HOUSE', quantity: 1, unitPrice: 180000, lineTotal: 180000, packageId: null, placeName: 'P. Xét nghiệm', note: null, status: 'ORDERED', editable: true },
    { id: 'i3', itemKind: 'TECHNICAL_SERVICE', technicalServiceId: null, examTypeCode: null, code: 'CD0008', name: 'Siêu âm ổ bụng tổng quát', performance: 'IN_HOUSE', quantity: 1, unitPrice: 420000, lineTotal: 420000, packageId: null, placeName: 'P. Siêu âm', note: null, status: 'ORDERED', editable: true },
    { id: 'i4', itemKind: 'TECHNICAL_SERVICE', technicalServiceId: null, examTypeCode: null, code: 'CD0021', name: 'Chụp CT scan bụng có thuốc cản quang', performance: 'EXTERNAL', quantity: 1, unitPrice: null, lineTotal: null, packageId: null, placeName: null, note: 'Nhịn ăn 6 giờ trước khi chụp', status: 'ORDERED', editable: true },
    { id: 'i5', itemKind: 'FREE_TEXT', technicalServiceId: null, examTypeCode: null, code: null, name: 'Đo mật độ xương DEXA cột sống thắt lưng', performance: 'EXTERNAL', quantity: 1, unitPrice: null, lineTotal: null, packageId: null, placeName: null, note: null, status: 'ORDERED', editable: true },
  ],
};
